"""autogenerated by genpy from mrp1_operator/Navroute_list.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mrp1_operator.msg

class Navroute_list(genpy.Message):
  _md5sum = "bb65302ba2b657633c82178c7f8050cc"
  _type = "mrp1_operator/Navroute_list"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """mrp1_operator/Navroute[] list
================================================================================
MSG: mrp1_operator/Navroute
mrp1_operator/Navpt pt1
mrp1_operator/Navpt pt2
================================================================================
MSG: mrp1_operator/Navpt
float64 longitude
float64 latitude
string tag
"""
  __slots__ = ['list']
  _slot_types = ['mrp1_operator/Navroute[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Navroute_list, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.list is None:
        self.list = []
    else:
      self.list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.list)
      buff.write(_struct_I.pack(length))
      for val1 in self.list:
        _v1 = val1.pt1
        _x = _v1
        buff.write(_struct_2d.pack(_x.longitude, _x.latitude))
        _x = _v1.tag
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _v2 = val1.pt2
        _x = _v2
        buff.write(_struct_2d.pack(_x.longitude, _x.latitude))
        _x = _v2.tag
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.list is None:
        self.list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list = []
      for i in range(0, length):
        val1 = mrp1_operator.msg.Navroute()
        _v3 = val1.pt1
        _x = _v3
        start = end
        end += 16
        (_x.longitude, _x.latitude,) = _struct_2d.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v3.tag = str[start:end].decode('utf-8')
        else:
          _v3.tag = str[start:end]
        _v4 = val1.pt2
        _x = _v4
        start = end
        end += 16
        (_x.longitude, _x.latitude,) = _struct_2d.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v4.tag = str[start:end].decode('utf-8')
        else:
          _v4.tag = str[start:end]
        self.list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.list)
      buff.write(_struct_I.pack(length))
      for val1 in self.list:
        _v5 = val1.pt1
        _x = _v5
        buff.write(_struct_2d.pack(_x.longitude, _x.latitude))
        _x = _v5.tag
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _v6 = val1.pt2
        _x = _v6
        buff.write(_struct_2d.pack(_x.longitude, _x.latitude))
        _x = _v6.tag
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.list is None:
        self.list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.list = []
      for i in range(0, length):
        val1 = mrp1_operator.msg.Navroute()
        _v7 = val1.pt1
        _x = _v7
        start = end
        end += 16
        (_x.longitude, _x.latitude,) = _struct_2d.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.tag = str[start:end].decode('utf-8')
        else:
          _v7.tag = str[start:end]
        _v8 = val1.pt2
        _x = _v8
        start = end
        end += 16
        (_x.longitude, _x.latitude,) = _struct_2d.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v8.tag = str[start:end].decode('utf-8')
        else:
          _v8.tag = str[start:end]
        self.list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d = struct.Struct("<2d")
