"""autogenerated by genpy from mrp1_operator/Navroute.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import mrp1_operator.msg

class Navroute(genpy.Message):
  _md5sum = "dbc2104495f306f455c882ffc5cbf688"
  _type = "mrp1_operator/Navroute"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """mrp1_operator/Navpt pt1
mrp1_operator/Navpt pt2
================================================================================
MSG: mrp1_operator/Navpt
float64 longitude
float64 latitude
string tag
"""
  __slots__ = ['pt1','pt2']
  _slot_types = ['mrp1_operator/Navpt','mrp1_operator/Navpt']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pt1,pt2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Navroute, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pt1 is None:
        self.pt1 = mrp1_operator.msg.Navpt()
      if self.pt2 is None:
        self.pt2 = mrp1_operator.msg.Navpt()
    else:
      self.pt1 = mrp1_operator.msg.Navpt()
      self.pt2 = mrp1_operator.msg.Navpt()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2d.pack(_x.pt1.longitude, _x.pt1.latitude))
      _x = self.pt1.tag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2d.pack(_x.pt2.longitude, _x.pt2.latitude))
      _x = self.pt2.tag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pt1 is None:
        self.pt1 = mrp1_operator.msg.Navpt()
      if self.pt2 is None:
        self.pt2 = mrp1_operator.msg.Navpt()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.pt1.longitude, _x.pt1.latitude,) = _struct_2d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pt1.tag = str[start:end].decode('utf-8')
      else:
        self.pt1.tag = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.pt2.longitude, _x.pt2.latitude,) = _struct_2d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pt2.tag = str[start:end].decode('utf-8')
      else:
        self.pt2.tag = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2d.pack(_x.pt1.longitude, _x.pt1.latitude))
      _x = self.pt1.tag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2d.pack(_x.pt2.longitude, _x.pt2.latitude))
      _x = self.pt2.tag
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pt1 is None:
        self.pt1 = mrp1_operator.msg.Navpt()
      if self.pt2 is None:
        self.pt2 = mrp1_operator.msg.Navpt()
      end = 0
      _x = self
      start = end
      end += 16
      (_x.pt1.longitude, _x.pt1.latitude,) = _struct_2d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pt1.tag = str[start:end].decode('utf-8')
      else:
        self.pt1.tag = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.pt2.longitude, _x.pt2.latitude,) = _struct_2d.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pt2.tag = str[start:end].decode('utf-8')
      else:
        self.pt2.tag = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2d = struct.Struct("<2d")
